from PyQt6.QtWidgets import QDialog,QVBoxLayout,QTabWidget,QWidget,QFormLayout,QComboBox,QSpinBox,QCheckBox,QLineEdit,QDialogButtonBox,QLabel
class GeneralSettingsDialog(QDialog):
    def __init__(self,profile,parent=None):
        super().__init__(parent);self.profile=profile;self.setWindowTitle("Station Settings");self.resize(650,560);root=QVBoxLayout(self);tabs=QTabWidget();root.addWidget(tabs)
        general=QWidget();f=QFormLayout(general);self.process=QLineEdit(profile.get('process_name',''));self.mode=QComboBox();self.mode.addItems(['manual','automatic']);self.mode.setCurrentText(profile.get('cycle_mode','manual'));self.sim=QCheckBox();self.sim.setChecked(profile.get('simulation',False));f.addRow('Process name',self.process);f.addRow('Cycle mode',self.mode);f.addRow('Simulation mode',self.sim);tabs.addTab(general,'GENERAL')
        timing=QWidget();f=QFormLayout(timing);self.window=QSpinBox();self.window.setRange(0,5000);self.window.setValue(profile.get('timing',{}).get('simultaneous_window_ms',300));f.addRow('Simultaneous event window (ms)',self.window);tabs.addTab(timing,'TIMING')
        alignment=QWidget();f=QFormLayout(alignment);self.align=QComboBox();self.align.addItems(['none','aruco']);self.align.setCurrentText(profile.get('alignment',{}).get('mode','none'));self.markers=QLineEdit(','.join(map(str,profile.get('alignment',{}).get('marker_ids',[]))));f.addRow('Alignment mode',self.align);f.addRow('Required ArUco IDs',self.markers);tabs.addTab(alignment,'ALIGNMENT')
        logging=QWidget();f=QFormLayout(logging);self.pass_img=QCheckBox();self.pass_img.setChecked(profile.get('logging',{}).get('save_pass_image',True));self.ng_img=QCheckBox();self.ng_img.setChecked(profile.get('logging',{}).get('save_ng_image',True));self.beep=QCheckBox();self.beep.setChecked(profile.get('ui',{}).get('beep',False));f.addRow('Save PASS image',self.pass_img);f.addRow('Save NG image',self.ng_img);f.addRow('Result beep',self.beep);tabs.addTab(logging,'LOGGING / UI')
        info=QWidget();f=QFormLayout(info);f.addRow(QLabel('Camera settings, ROI detection, and process sequence are configured from their dedicated engineering tools.'));tabs.addTab(info,'ROI / DETECTION')
        b=QDialogButtonBox(QDialogButtonBox.StandardButton.Save|QDialogButtonBox.StandardButton.Cancel);b.accepted.connect(self.accept);b.rejected.connect(self.reject);root.addWidget(b)
    def apply(self):
        p=self.profile;p['process_name']=self.process.text();p['cycle_mode']=self.mode.currentText();p['simulation']=self.sim.isChecked();p.setdefault('timing',{})['simultaneous_window_ms']=self.window.value();p['alignment']={'mode':self.align.currentText(),'marker_ids':[int(x) for x in self.markers.text().split(',') if x.strip().isdigit()]};p['logging']={'save_pass_image':self.pass_img.isChecked(),'save_ng_image':self.ng_img.isChecked()};p['ui']={'beep':self.beep.isChecked()}
